namespace Domain.Enums;

public enum CodePrefix
{
    AccessGroup = 1,
    AddressBook,
    AddressContact,
    ChargeCategory,
    ChargeCode,
    ChargeUnit,
    ControlCode,
    CycleCount,
    Inbound,
    InboundUpload,
    InventoryAdjustment,
    Invoice,
    MiscelleneousCharges,
    Other,
    Outbound,
    OutboundUpload,
    PackageType,
    Packing,
    PaymentTerm,
    ProductCode,
    Quarantine,
    Relocation,
    ShippingTerm,
    Split,
    StorageCharges,
    StockTransfer,
    SystemResource,
    Traffic,
    Truck,
    UOM,
    FixCharge,
    Decant,
    InboundReversal,
    OutboundReversal,
    AdjustmentReversal,
    StockTransferReversal,
    StockTakeByLoc,
    JobAllocation,
    JobQueue,
    CycleCountUpload,
    StockTransferUpload,
    Loading = 42,
    ExtIn,
    ExtOut,
    PalletTransferRequest
}
