using System.Collections.Generic;
using System.Text.Json;

namespace TT.Services.Services.Utilities
{
    public class JsonResultError
    {
        public JsonResultError()
        {
            Arguments = new Dictionary<string, string>();
        }

        public JsonResultError(string messageKey) : base()
        {
            MessageKey = messageKey;
        }

        public JsonResultError(string messageKey, string key, string value)
        {
            MessageKey = messageKey;
            Arguments = new Dictionary<string, string>() { { key, value } };
        }


        public string MessageKey { get; set; }
        public Dictionary<string, string> Arguments { get; set; }

        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// TODO to be removed once all strings moved to UI
        /// </summary>
        public static Dictionary<string, string> TranslationsEN = new Dictionary<string, string>()
        {
            {"UnableToRetrieveLoadingInstance", "Unable to retrieve Loading instance." },
            {"CannotGenerateLoadingDetailsFromSelectedOutbound_RETURN.", "Cannot generate loading details from the selected outbound - some outbounds are of type RETURN." },
            {"CannotGenerateLoadingDetailsFromSelectedOutbound_CANCELLED", "Cannot generate loading details from the selected outbound - some outbounds are of status CANCELLED." },
            {"CannotGenerateLoadingDetailsFromSelectedOutbound", "Cannot generate loading entries from the selected outbound - some outbounds selected cannot be used for loading." },
            {"RecordNotFound", "Record not found" },
            {"FollowingOutboundJobsNotPicked__", "The following Outbound jobs has not been picked: {jobNos}" },
            {"FailToCargoOut", "Fail to Cargo Out, please contact System Administrator" },
            {"UnableToLoadLoadingDetailContactAdmin", "Unable to load Loading Detail. Please contact System Administrator." },
            {"CompleteOutboundReturnFailContactAdmin", "Complete outbound RETURN fail. Please Contact System Administrator." },
            {"FailToCompleteManualOutboundContactAdmin", "Fail to complete Manual Outbound, please contact System Administrator." },
            {"InvalidOutboundJobType", "Invalid outbound job type, please try again." },
            {"FollowingOutboundJobsNotCargoOut__", "The following Outbound jobs has not been cargo out: {jobNos}" },
            {"LoadingJobCannotBeCancelled__", "Loading job {jobNo} with {loadingStatus} status cannot be cancelled" },
            {"LoadingJobWithDetailsCannotBeCancelled__", "Loading job [{jobNo}] with loading details cannot be cancelled. Please delete all loading details before cancel." },
            {"LoadingDetailNotFoundForJobNoOrderNo__", "Loading detail not found for job no: {jobNo}, order no: {orderNo}" },
            {"OrderNosCannotBeEmpty", "Order nos cannot be empty" },
            {"DeliveryDocketPrintError_Confirmed", "Delivery Docket can ONLY be printed after Loading job is CONFIRMED! You have to confirm and CARGO OUT all outbound before you can print the Delivery Docket!" },
            {"CannotCreateQRCodeForOutbound__", "Cannot create QR Code for Outbound {outJobNo}: {error}" },
            {"CannotPrintReportOwnerNotTESA", "Cannot print this report - Owner Code is not TESA" },
            {"CannotAddOrRemoveOutboundsToLoadingJobInStatusCompleted", "You cannot add or remove details to or from a completed Loading"},

            {"ErrorRetrievingEKanban__", "Error retrieving EKanban {orderNo}." },
            {"FailToLoadInventoryForCustomer__", "Fail to load Inventory control instance for customer {customerCode}." },
            {"ThereAreItemsInPickingListPleaseUndo", "There are items in picking list, please undo picking list before cancel this job." },
            {"InvalidEKanbanHeaderStatus", "Invalid EKanbanHeader status." },
            {"ImportErrorsOccurred__", "Some errors occurred when importing the following orderNumbers: {orderNos}." },
            {"CannotFindOutboundForJobNo__", "Cannot find outbound for jobNo {jobNo}." },
            {"InvalidJobTypeForJobNo__","Invalid job type for job no {jobNo}." },
            {"EmptyPickingListForJobNo__", "Empty picking list is generated for job no {jobNo}." },
            {"CompleteReturnFailProductNotScanned", "The product has not been scanned (miss picking step), Complete Return Fail." },
            {"FailToRetrieveStorageDetailForPID__", "Fail to retrieve Storage Detail Instance for PID {pid}." },
            {"FailToRetrieveInboundForPID__", "Fail to retrive Inbound for PID {pid}." },
            {"InboundJobNotCompletedForPID__", "Inbound job {jobNo} of PID {pid} is not completed." },
            {"FailToRetrieveInventoryInstance", "Fail to retrieve Inventory Instance." },
            {"InvalidCartonQtyForPID__", "Invalid carton quantity for PID {pid} after dispatch" },
            {"InvalidAllocatedQtyForPID__", "Invalid allocated quantity for PID {pid} after dispatch" },
            {"FailToRetrieveInventoryForProductCode__", "Fail to retrieve last inventory transaction for Product Code {productCode}"  },
            {"InvalidBalanceQty", "Invalid BALANCE QUANTITY in inventory transaction" },
            {"FailToRetrieveLastInventoryTransaction", "Fail to retrieve Last Inventory Warehouse Transaction by supplier." },
            {"EmptyOutboundDetailForJobNo__", "Empty outbound detail for job no {jobNo}" },
            {"NoPickingListForJobLine__", "No picking list data for job no: { jobNo}, line item: {lineItem }." },
            {"CargoOutFailSomeItemMissing__", "Some item for [{productCode}][{supplierID}] has not been scanned(miss picking step), Cargo Out Fail." },
            {"CargoOutFailInvalidPicked__", "Invalid picked item: PID [{pid}], LineItem[{lineItem}], Cargo Out Fail." },
            {"CargoOutFailInvalidStatus__", "Inbound [{inbound}] for PID [{pid}] is [{status}], Cargo Out Fail." },
            {"CargoOutFailInvalidPickedQty__", "Invalid picked qty for PID [{pid}], Cargo Out Fail." },
            {"CargoOutFailInvalidWHSCode__", "Invalid Whscode: Outbound[{outboundWhs}], PID [{plWhs}] ; Cargo Out Fail." },
            {"CargoOutFailInvalidOutboundJobNo__", "Invalid OutboundJobNo: Outbound[{outbound}], PID [{pid}] ; Cargo Out Fail." },
            {"CargoOutFailInvalidCustomerCode__", "Invalid CustomerCode: Outbound[{outbound}], PID [{pid}] ; Cargo Out Fail." },
            {"CargoOutFailInvalidItem__", "Invalid picking list item [{lineItem}][{productCode}][{supplierID}], Cargo Out Fail." },
            {"CargoOutFailInvalidPickedQtyForOutbound__", "Invalid picked quantity: OutboundDetail Quantity [{qty}], OutboundDetail PickedQty[{pickedQty}] , PickingList Quantity[{totalQty}], Cargo Out Fail." },
            {"CargoOutFailInvalidDetail", "PickingList do not match OutboundDetail, Cargo Out Fail." },
            {"OutboundJobCreateError", "Error in creating new outbound job." },
            {"ImportEKanbanListEmptyError", "List of  Order Detail by Product Code/Supplier is empty." },
            {"ImportEKanbanUnableToRetrievePartMaster", "Unable to retrieve part master." },
            {"ImportEKanbanUnableToRetrieveDetail", "Error in retrieving eKanban detail list." },
            {"UnableToCancelOrderImported__", "Unable to cancel {orderNo}! The order is IMPORTED!" },
            {"UnableToImportOrderImported__", "Unable to import {orderNo}! The order is IMPORTED! [{importedJobNo}]" },
            {"UnableToImportOrderVMISuppliers__", "Unable to import [{orderNo}]! The order contains VMI Suppliers. Please use E-KANBAN from Electrolux. VMI Suppliers: {suppliers}" },
            {"NoPartNoFoundForOrder__", "NO Part Number was found for this Order No [{orderNo}]! The Order is EMPTY, please report this matter to Technical Support!" },
            {"ProductCodeNotFoundInPartMaster__", "[{productCode}] is not found in the Part Master!" },
            {"SupplierMasterNotFound__", "Supplier master for SupplierID=[{supplierID}] & FactoryID=[{factoryId}] is not found!" },
            {"EKanbanExists", "EKanban detail already exists." },
            {"OutboundNotFoundForJob__", "Outbound for job no {jobNo} was not found." },
            {"DuplicateProductForSupplier__", "Product Code: {productCode} for {supplierID} already existed in the outbound detail list, please type with other product code or supplier." },
            {"OutboundDetailNotFound__", "Outbound detail for job no {jobNo}, line item {lineItem} was not found." },
            {"SplitError__", "Outbound job with status {status} cannot split." },
            {"SplitTypeError__", "Outbound job with type {type} cannot split." },
            {"FailToGenerateOutboundJobNo", "Fail to generate Outbound Job No." },
            {"FailToRetrieveOutboundDetail", "Fail to retrive outbound detail." },
            {"OutboundStatusCannotCancel__", "Outbound status {status} cannot cancel allocation." },
            {"ItemPickedPleaseUnpick", "One of the selected picking list item has been picked. Please undo picking first." },
            {"NoAllocatedPIDToRemove", "No allocated PID to remove" },
            {"NotEnoughQtyInEKanbanNotEnoughQtyInEKanban", "Not enough supplied quantity in ekanban detail." },
            {"NegativeAllocatedQtyForPID__", "Negative Allocated Qty for PID [{pid}]" },
            {"OutboundOrderItemForJobLineNotFound__", "Outbound order item for job no {jobNo} and line {lineItem} was not found." },
            {"FailedToDeleteOutboundOrderItem", "Fail to delete Outbound Order Item. Please release the picking items" },
            {"CannotDeleteOutboundJobCompleted", "You are not allow to delete outbound detail for Completed outbound job." },
            {"SelectedPIDsNotPickedOrPacked", "Selected PIDs are not in Picked or Packed status." },
            {"CannotFindPickingItemFromStorageMaster", "System couldn't find Picking Item from Storage Master File." },
            {"PidNotAllocatedByOutJob__", "PID {pid} wasn't allocated by OutJobNo {jobNo} in Storage Master File." },
            {"PidInvalidStatus__", "PID {pid} has invalid status {status}" },
            {"FailToRetireveInvTransactionPerWHS","Unable to retrieve InvTransactionPerWHS" },
            {"PickingListNotFound__","Picking list {plNo} not found." },
            {"PickingListHasNoPID__","Picking list {plNo} has no PID" },
            {"StorageNotFound__","Storage {pid} not found." },
            {"PleaseAddPartForDelivery","Please add a part for delivery." },
            {"ErrorRetrievingStorageDetail","Error retrieving StorageDetail" },
            {"ErrorRetrievingOutboundDetail","Error retrieving OutboundDetail" },
            {"CantFindPickingItemFromStorageMaster","System couldn't find Picking Item from Storage Master File." },
            {"NegativePickingQty","Negative Picking Qty exists in Outbound Detail after Undo Picking" },
            {"InvalidIndicationInformation","Invalid indication information" },
            {"InventoryNotFound","Inventory not found" },
            {"JobCodeCannotBeFound","Job Code cannot be found" },
            {"ExcelImportInputAtLEastOneEKanban","Please input at least one EKANBAN to import in EXCEL file." },
            {"NoFilesToParse","No files to parse" },

            {"AtLeastOneOutboundJobNoMustBeSpecified", "At least one Outbound Job No must be specified and all Job Nos cannot be empty" },
            {"AtLeastOneOrderNoMustBeSpecified", "At least one Order No must be specified and all Order Nos cannot be empty" },
            {"AtLeastOneJobNoMustBeSpecified", "At least one Job No must be specified and all Job Nos cannot be empty" },
            {"WHSCodeCannotBeEmpty", "WHSCode cannot be empty" },
            {"WHSCodeCannotExceedChars", "WHSCode cannot exceed 7 characters" },
            {"CustomerCodeCannotBeEmpty", "Customer Code cannot be empty" },
            {"CustomerCodeCannotExceedChars", "Customer Code cannot exceed 10 characters" },
            {"RefNoCannotBeEmpty", "RefNo cannot be empty" },
            {"RefNoCannotExceedChars", "RefNo cannot exceed 30 characters" },
            {"RemarksCannotExceedChars", "Remarks cannot exceed 100 characters" },
            {"JobNoCannotBeEmpty", "JobNo cannot be empty" },
            {"JobNoCannotExceedChars", "JobNo cannot exceed 15 characters" },
            {"WHSCodeCannotBeEmpty", "WHSCode cannot be empty" },
            {"WHSCodeCannotExceedChars", "WHSCode cannot exceed 7 characters" },
            {"OSNoCannotExceedChars", "OSNo cannot exceed 15 characters" },
            {"NewWHSCodeCannotBeEmpty", "New WHSCode cannot be empty" },
            {"CommInvNoCannotExceedChars", "Comm Inv No cannot exceed 1292 characters" },
            {"DeliveryToCannotExceedChars", "Delivery To cannot exceed 20 characters" },
            {"PickingQtyMustBeGreaterThan0", "Picking qty must be greater than 0" },
            {"PickingQtyMustBeLessEqualThanAvQty", "Picking qty must be equal or less than available qty" },
            {"SelectSupplierID", "Please select a SupplierID" },
            {"LineNoCannotBeZero", "Line No cannot be zero" },
            {"ProductCodeCannotBeEmpty", "Product code cannot be empty" },
            {"PIDCannotBeEmpty", "PID cannot be empty" },
            {"SupplierCannotBeEmpty", "Supplier cannot be empty" },
            {"LocationCannotBeEmpty", "Location cannot be empty" },
            {"InboundDateCannotBeEmpty", "Inbound date cannot be empty" },
            {"MasterPIDQtyMustBeSpecified", "Master PID Qty must be specified for ownership split" },
            { "OutboundHasMixedOwnership__", "The outbound {jobNo} has mixed ownership, cannot complete." },
            {"NoPIDInPickingList","There is no PID in picking list" },
            {"SplitFailedOneInboudDateOnly", "Unable to split as there is only one inbound date." },
            {"SplitFailedOneInboudJobOnly", "Unable to split as there is only one inbound job." },

            {"UnableToImportASNWithStatus__", "Unable to import ASN {asnNo} with status {status}." },
            {"ASNNoDoesNotContainASNDetail__","{asnNo} does not contain any ASN Detail." },
            {"ProductCodeNotRegisteredInPartsMaster__","{productCode} not registered in PartsMaster!" },
            {"ProductCodeHasInvalidSPQ__","{productCode} has invalid SPQ!" },
            {"ProductCodeHasInvalidQty__","{productCode} has invalid Qty (No Of Outer x Qty per Outer)!" },
            {"FailToRetrievePID__","Fail to retrieve new PID for {jobNo}" },

            {"IRNoCannotBeEmpty","IRNo cannot be empty" },
            {"IRNoCannotExceedChars","IRNo cannot exceed 25 chars" },
            {"SupplierIDCannotBeEmpty","SupplierID cannot be empty" },
            {"SupplierIDCannotExceedChars","SupplierID cannot exceed 25 chars" },
            {"TransTypeMustBeManualExcessOrReturn","Inbound type must be Manual, Excess or Return." },
            {"InvalidCurrency","Invalid currency." },
            {"ProductCodeCannotExceedChars","ProductCode cannot exceed 30 chars" },
            {"PackageTypeCannotBeEmpty","PackageType cannot be empty" },
            {"PackageTypeCannotExceedChars","PackageType cannot exceed 7 chars" },
            {"QtyMustBeGreaterThanZero","Qty must be greater than zero" },
            {"ProvideValidEntryQtyDivisableByPackage","Please provide a valid Entry Quantity(Divisable by Package)" },
            {"ProvideValidEntryQtyDivisableByLabel","Please provide a valid Entry Quantity(Divisable by No Of Label)" },
            {"ProvideValidEntryQtyDivisableToQty","Please provide a valid Quantity Per Package (Divisible to Qty)" },
            {"UnableToAddOutstandingCycleCount__","Unable to add. Reason : There is/are outstanding CYCLE COUNT job(s). Action : Please complete the following outstanding job(s) before proceeding: {jobNos}" },
            {"InvalidInboundDetailQty","Invalid Inbound Detail Qty" },
            {"InvalidStorageDetailSummary","Invalid StorageDetail summary" },
            {"FailToCreateQuarantineJobNo","Fail to create new Quarantine Job No." },
            {"FailToRetrieveInventoryInstanceForProductCode__","Fail to retrieve Inventory Instance for {productCode}." },
            {"AtLeastOnePIDMustBeSpecified","At least one PID must be specified and all PIDs cannot be empty" },
            {"DiscrepancyReport_PrintErrorNotASN","Fail to generate Discrepancy Report as records are not ASN Import." },
            {"CannotSaveRecordIsCancelled", "Cannot save, the record status is Cancelled." },
            {"InboundJobCannotBeCancelled__", "Inbound job {jobNo} cannot be cancelled." },
            {"AtLeastOneContainerNoMustBeSpecified", "At least one container no must be specified." },
            {"CurrencyCannotBeEmpty", "Currency cannot be empty." },
            {"PleaseSelectLineToUpdate", "Please select line to update." },
            {"FieldCannotBeEmpty", "Field cannot be empty." },
            {"PasswordIsRequired","Password is required." },
            {"UsernameIsRequired","Username is required." },
            {"IncorrectLineItem","Incorrect LineItem number." },
            {"NoPIDAvailableForOutboundStockTransfer", "There is no PID data available for this Outbound/StockTransfer job." },
            {"YouHavePickedMoreThanOrderQty", "You have picked more than order quantity. Allocation operation stopped." },
            {"FailToReleaseBondedStockCommInvNoEmpty","Fail to Release Bonded stock, Commercial Invoice No is empty." },
            { "NoBondedStock", "There is no Bonded stock can be released" },
            { "PartMasterAlreadyExists", "Part Master already exists." },
            { "FailedToRetrieveUOM", "Failed to retrieve UOM." },
            {"CPartSPQIncorrectQty","SPQ is not divisible by C-Part SPQ." },
            {"DescriptionCannotBeEmpty","Description cannot be empty." },
            {"UOMCannotBeEmpty","UOM cannot be empty." },
            {"OriginCountryCannotBeEmpty","Origin Country cannot be empty." },
            {"SPQMustBeGreaterThan0","SPQ must be greater than 0." },
            {"OrderLotMustBeGreaterThan0","Order Lot must be greater than 0." },
            {"LengthMustBeGreaterThan0","Length must be greater than 0." },
            {"WidthMustBeGreaterThan0","Width must be greater than 0." },
            {"HeightMustBeGreaterThan0","Height must be greater than 0." },
            {"NetWeightMustBeGreaterThan0","Net Weight must be greater than 0." },
            {"GrossWeightMustBeGreaterThan0","Gross Weight must be greater than 0." },
            {"CPartSPQMustBeGreaterThan0","SPQ must be greater than 0." },
            {"iLogReadinessStatusMustBeOneOfDefined","iLog Readiness Status must be one of predefined values." },
            {"PalletTypeMustBeOneOfDefined","Pallet Type must be one of predefined values." },
            {"UnloadingPointDoesNotExist","This unloading point does not exist for this customer." },
            {"CPartCantBeMixed", "CPart product cannot be marked as mixed." },
            {"PasswordsDoNotMatch","Passwords do not match." },
            {"RefNoCannotExceed20Chars", "RefNo cannot exceed 20 characters" },
            {"StockTransferCannotBeCancelledCompleted.","Stock Transfer Cannot be cancelled as it had already been completed." },
            {"StockTransferCannotBeCancelledCancelled","Stock Transfer Cannot be cancelled as it had already been cancelled." },
            {"StockTransferCannotBeCancelledProcessing","Stock Transfer Cannot be cancelled as it is processing, please remove PIDs and try again." },
            {"FailToCancelStockTransferRemovePIDs", "Fail to Cancel job {jobNo}. Please remove all PID from this job first." },
            {"StockTransferCannotBeCompletedDetailsEmpty","Stock Transfer Cannot be confirmed as Stock Transfer Detail is empty." },
            {"StockTransferCannotBeCompletedConfirmed","Stock Transfer Cannot be confirmed as it had already been completed." },
            {"FailToRetrieveStorageDetailForPID","Fail to retrieve Storage Detail Instance for PID {pid}." },
            {"FailToRetrieveEStockTransferForRefNo","Fail to load EStockTrasferHeader Instance for {refNo}" },
            {"CannotSplitInvalidStatus", "Cannot split - invalid status." },
            {"CannotSplitNoDetails", "Cannot split - there must be at least 2 inbound dates associated with the records." },
            {"StorageNotFoundOrNotPutawayOrNotOwnedBySupplier","Storage not found or not putaway, or not owned by supplier." },
            {"CannotCompleteStockTranferStorageIsInStatusIncoming","Cannot complete stock tranfer - storage {pid} is in status Incoming." },
            {"CannotCompleteStockTranferInboundNotCompleted","Cannot complete stock tranfer - inbound {jobNo} is not Completed." },
            {"LockedBy__", "This document is locked by {userCode}." },
            {"ItemAlreadyPicked__", "Item {pid} is already picked." }

        };
    }
}
