CREATE TABLE dbo.[TT_ReportPrintingLog]  
   (Id UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
   JobNo VARCHAR(15) NOT NULL,  
   ReportName NVARCHAR(100) NOT NULL,  
   PrintedDate DATETIME NOT NULL,
   PrintedBy VARCHAR(10) NOT NULL)
