CREATE TABLE [dbi].[SAPStorageLocationMapping](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FactoryID] [nvarchar](7) NOT NULL,
	[WHCode] [nvarchar](7) NOT NULL,
	[IsEHP] [bit] NOT NULL,
	[StorageLocation] [nvarchar](4) NOT NULL,
 CONSTRAINT [PK_SAPStorageLocationMapping] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC_FactoryWHIsEHP] UNIQUE NONCLUSTERED 
(
	[FactoryID] ASC,
	[WHCode] ASC,
	[IsEHP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO