CREATE TABLE [dbo].[ASNCarrierMapping](
	[Prefix] [varchar](10) NOT NULL,
	[ShippingLineName] [varchar](50) NOT NULL,
	[SCAC] [varchar](4) NOT NULL,
 CONSTRAINT [PK_ASNCarrierMapping] PRIMARY KEY CLUSTERED 
(
	[Prefix] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT [dbo].[ASNCarrierMapping] ([Prefix], [ShippingLineName], [SCAC]) VALUES
(N'ACLU', N'ACL', N'ACLU'),
(N'ACLZ', N'ACL', N'ACLU'),
(N'ACTU', N'MAERSK', N'MAEU'),
(N'ACXU', N'GRIEG STAR SHIPPING', N'GSSW'),
(N'AJCU', N'MAERSK', N'MAEU'),
(N'AKLU', N'K-LINE', N'KKLU'),
(N'ALNU', N'CARU', N'WEDU'),
(N'AMCU', N'CMA CGM', N'CMDU'),
(N'AMFU', N'Textainer', N'TEXU'),
(N'AMZU', N'ZIM', N'ZIMU'),
(N'ANB', N'ANL', N'ANNU'),
(N'ANC', N'ANL', N'ANNU'),
(N'ANE', N'ANL', N'ANNU'),
(N'ANF', N'ANL', N'ANNU'),
(N'ANNU', N'ANL', N'ANNU'),
(N'ANR', N'ANL', N'ANNU'),
(N'APDU', N'APL', N'APLU'),
(N'APHU', N'APL', N'APLU'),
(N'APIU', N'APL', N'APLU'),
(N'APLS', N'APL', N'APLU'),
(N'APLU', N'APL', N'APLU'),
(N'APMU', N'MAERSK', N'MAEU'),
(N'APRU', N'APL', N'APLU'),
(N'APZU', N'APL', N'APLU'),
(N'ARCU', N'Sunmarine', N'BAXU'),
(N'ARDU', N'CARU', N'WEDU'),
(N'ARKU', N'Arkas', N'ARKU'),
(N'ARTU', N'CARU', N'WEDU'),
(N'ATKU', N'CAI', N'CAXU'),
(N'AXIU', N'Textainer', N'TEXU'),
(N'AZLU', N'HAPAG (HL)', N'HPGC'),
(N'BAXU', N'Sunmarine', N'BAXU'),
(N'BBUU', N'MAERSK', N'MAEU'),
(N'BEAU', N'Beacon Intermodal', N'BMOU'),
(N'BHCU', N'Bridgehead', N'BHCU'),
(N'BLJU', N'Balaji Shipping', N'BLJU'),
(N'BMOU', N'Beacon Intermodal', N'BMOU'),
(N'BMSU', N'BMC Line', N'BMSU'),
(N'BOLU', N'GRIEG STAR SHIPPING', N'GSSW'),
(N'BSHB', N'GESeaCo', N'GESU'),
(N'BSIU', N'Blue Sky', N'BSIU'),
(N'BSLU', N'MAERSK', N'MAEU'),
(N'BSPD', N'GESeaCo', N'GESU'),
(N'BSTG', N'GESeaCo', N'GESU'),
(N'CAAU', N'CAI', N'CAXU'),
(N'CACU', N'HAPAG (HL)', N'HPGC'),
(N'CADU', N'Hamburg Sud', N'SUDU'),
(N'CAEU', N'CARU', N'WEDU'),
(N'CAIU', N'CAI', N'CAXU'),
(N'CARU', N'CARU', N'WEDU'),
(N'CASU', N'HAPAG (HL)', N'HPGC'),
(N'CATU', N'CARU', N'WEDU'),
(N'CAXU', N'CAI', N'CAXU'),
(N'CAZU', N'CAI', N'CAXU'),
(N'CBHU', N'COSCO', N'COSU'),
(N'CCLU', N'CHINA SHIPPING', N'CHNJ'),
(N'CEOU', N'Textainer', N'TEXU'),
(N'CESU', N'CAI', N'CAXU'),
(N'CGHU', N'CMA CGM', N'CMDU'),
(N'CGMU', N'CMA CGM', N'CMDU'),
(N'CGTU', N'CMA CGM', N'CMDU'),
(N'CHIU', N'Textainer', N'TEXU'),
(N'CIPU', N'CAI', N'CAXU'),
(N'CLCU', N'CARU', N'WEDU'),
(N'CLHU', N'Textainer', N'TEXU'),
(N'CLOU', N'GESeaCo', N'GESU'),
(N'CMAU', N'CMA CGM', N'CMDU'),
(N'CMBU', N'Safmarine', N'SAFM'),
(N'CMCU', N'Crowley', N'CMCU'),
(N'CMNU', N'CMA CGM', N'CMDU'),
(N'CMUU', N'HAPAG (HL)', N'HPGC'),
(N'CNCU', N'CMA CGM', N'CMDU'),
(N'CNEU', N'CN', N'TTWZ'),
(N'CNGU', N'CN', N'TTWZ'),
(N'CNIU', N'CCNI', N'CNIU'),
(N'CNPU', N'CN', N'TTWZ'),
(N'CNRU', N'CN', N'TTWZ'),
(N'CNSU', N'CN', N'TTWZ'),
(N'COAU', N'COSCO', N'COSU'),
(N'COCU', N'Samskip', N'SKII'),
(N'COHU', N'COSCO', N'COSU'),
(N'CORU', N'CARU', N'WEDU'),
(N'COSU', N'COSCO', N'COSU'),
(N'COZU', N'MAERSK', N'MAEU'),
(N'CPPU', N'CP', N'CPRS'),
(N'CPSU', N'HAPAG (HL)', N'HPGC'),
(N'CRLU', N'SeaCastle Inc', N'INBU'),
(N'CRSU', N'Cronos', N'LPIU'),
(N'CRTU', N'Cronos', N'LPIU'),
(N'CRXU', N'Cronos', N'LPIU'),
(N'CSHU', N'MAERSK', N'MAEU'),
(N'CSLU', N'CHINA SHIPPING', N'CHNJ'),
(N'CSNU', N'COSCO', N'COSU'),
(N'CSQU', N'HAPAG (HL)', N'HPGC'),
(N'CSSU', N'MAERSK', N'MAEU'),
(N'CSVU', N'CSAV NORASIA', N'NSLU'),
(N'CSYU', N'Textainer', N'TEXU'),
(N'CTWU', N'SeaCastle Inc', N'INBU'),
(N'CUBU', N'CARU', N'WEDU'),
(N'CUCU', N'Cronos', N'LPIU'),
(N'CULU', N'China United Lines', N'CUTW'),
(N'CXCU', N'Matson', N'MATS'),
(N'CXDU', N'GESeaCo', N'GESU'),
(N'CXRU', N'GESeaCo', N'GESU'),
(N'CXSU', N'GESeaCo', N'GESU'),
(N'CXTU', N'GESeaCo', N'GESU'),
(N'CZZU', N'CAI', N'CAXU'),
(N'DALU', N'HAPAG (HL)', N'HPGC'),
(N'DAMU', N'CARU', N'WEDU'),
(N'DAYU', N'DAL', N'DAYU'),
(N'DDCU', N'DAL', N'DAYU'),
(N'DEDU', N'SeaCastle Inc', N'INBU'),
(N'DFOU', N'Florens', N'FBIU'),
(N'DFSU', N'Florens', N'FBIU'),
(N'DGFU', N'DHL', N'DHLC'),
(N'DHZU', N'DHL', N'DHLC'),
(N'DJLU', N'Dongjin Shipping', N'DJLU'),
(N'DLLU', N'Textainer', N'TEXU'),
(N'DNAU', N'GESeaCo', N'GESU'),
(N'DNLU', N'Hamburg Sud', N'SUDU'),
(N'DOLU', N'Dolphin Line', N'DLPL'),
(N'DPLU', N'DHL', N'DHLC'),
(N'DRYU', N'SeaCastle Inc', N'INBU'),
(N'DSAU', N'Pollux & Castor', N'DSAU'),
(N'DVRU', N'Delmas', N'DVRU'),
(N'DYLU', N'Dong Young Shipping', N'PCSU'),
(N'EAB', N'ANL', N'ANNU'),
(N'EAC', N'ANL', N'ANNU'),
(N'EAE', N'ANL', N'ANNU'),
(N'EAF', N'ANL', N'ANNU'),
(N'EANU', N'Alianca', N'ANRM'),
(N'EAR', N'ANL', N'ANNU'),
(N'EASU', N'Waterfront Container', N'WFHU'),
(N'EBCU', N'Florens', N'FBIU'),
(N'ECMU', N'CMA CGM', N'CMDU'),
(N'ECMV', N'CMA CGM', N'CMDU'),
(N'ECNU', N'Econ Shipping', N'ECNU'),
(N'EGHU', N'EVERGREEN', N'EGLV'),
(N'EGSU', N'EVERGREEN', N'EGLV'),
(N'EISU', N'EVERGREEN', N'EGLV'),
(N'EITU', N'EVERGREEN', N'EGLV'),
(N'EKLU', N'K-LINE', N'KKLU'),
(N'ELOU', N'MACS', N'ELOU'),
(N'EMAU', N'GESeaCo', N'GESU'),
(N'EMCU', N'EVERGREEN', N'EGLV'),
(N'ENAU', N'Hamburg Sud', N'SUDU'),
(N'EQRU', N'Triton Container', N'YOIU'),
(N'ESDU', N'ESL', N'ESPU'),
(N'ESLU', N'ESL', N'EULU'),
(N'ESPU', N'ESL', N'ESPU'),
(N'ESSU', N'K-LINE', N'KKLU'),
(N'EXFU', N'Hamburg Sud', N'SUDU'),
(N'EYIU', N'Triton Container', N'YOIU'),
(N'FAAU', N'MAERSK', N'MAEU'),
(N'FACU', N'Florens', N'FBIU'),
(N'FANU', N'HAPAG (HL)', N'HPGC'),
(N'FBIU', N'Florens', N'FBIU'),
(N'FBLU', N'Florens', N'FBIU'),
(N'FCCU', N'FESCO', N'FESO'),
(N'FCDU', N'Florens', N'FBIU'),
(N'FCGU', N'Florens', N'FBIU'),
(N'FCIU', N'APL', N'APLU'),
(N'FCLU', N'Florens', N'FBIU'),
(N'FCRU', N'Finnlines', N'FLFU'),
(N'FCXU', N'Florens', N'FBIU'),
(N'FESU', N'FESCO', N'FESO'),
(N'FFAU', N'Florens', N'FBIU'),
(N'FFFU', N'Florens', N'FBIU'),
(N'FJKU', N'Florens', N'FBIU'),
(N'FLCU', N'Finnlines', N'FLFU'),
(N'FLFU', N'Finnlines', N'FLFU'),
(N'FLRU', N'Finnlines', N'FLFU'),
(N'FLXU', N'Flexi-Van', N'FLGZ'),
(N'FMGU', N'HAPAG (HL)', N'HPGC'),
(N'FOCU', N'Focus Trucking', N'FCSK'),
(N'FRLU', N'MAERSK', N'MAEU'),
(N'FSB', N'ANL', N'ANNU'),
(N'FSC', N'ANL', N'ANNU'),
(N'FSCU', N'Florens', N'FBIU'),
(N'FSE', N'ANL', N'ANNU'),
(N'FSR', N'ANL', N'ANNU'),
(N'FTAU', N'Florens', N'FBIU'),
(N'FVGU', N'Flexi-Van', N'FLGZ'),
(N'FVIU', N'GESeaCo', N'GESU'),
(N'FWLU', N'Florens', N'FBIU'),
(N'GAEU', N'Textainer', N'TEXU'),
(N'GAFU', N'MACS', N'ELOU'),
(N'GAOU', N'SeaCastle Inc', N'INBU'),
(N'GATU', N'Textainer', N'TEXU'),
(N'GAZU', N'Textainer', N'TEXU'),
(N'GBEU', N'Safmarine', N'SAFM'),
(N'GBLU', N'Safmarine', N'SAFM'),
(N'GCDU', N'MAERSK', N'MAEU'),
(N'GCEU', N'GESeaCo', N'GESU'),
(N'GCNU', N'Grimaldi', N'GM'),
(N'GESU', N'GESeaCo', N'GESU'),
(N'GETU', N'Tarros', N'GETU'),
(N'GU', N'GRIEG STAR SHIPPING', N'GSSW'),
(N'GIPU', N'SeaCastle Inc', N'INBU'),
(N'GLDU', N'LD', N'GLDU'),
(N'GLSU', N'ZIM', N'ZIMU'),
(N'GNRP', N'HYUNDAI', N'HDMU'),
(N'GNSU', N'Samskip', N'SKII'),
(N'SU', N'ld Star Line', N'GSLU'),
(N'GRDU', N'LD', N'GLDU'),
(N'GRIU', N'Hamburg Sud', N'SUDU'),
(N'GSLU', N'ld Star Line', N'GSLU'),
(N'GSPU', N'SeaCastle Inc', N'INBU'),
(N'GSSU', N'GRIEG STAR SHIPPING', N'GSSW'),
(N'GSTU', N'ZIM', N'ZIMU'),
(N'GSXU', N'ld Star Line', N'GSLU'),
(N'GTIU', N'MSC', N'MSCU'),
(N'GUTU', N'UES', N'UETU'),
(N'GVCU', N'UES', N'UETU'),
(N'GVDU', N'UES', N'UETU'),
(N'HAKU', N'CARU', N'WEDU'),
(N'HALU', N'Heung-A Shipping', N'11QU'),
(N'HAMU', N'HAPAG (HL)', N'HPGC'),
(N'HARU', N'Heung-A Shipping', N'11QU'),
(N'HASU', N'MAERSK', N'MAEU'),
(N'HCIU', N'Textainer', N'TEXU'),
(N'HDLU', N'Safmarine', N'SAFM'),
(N'HDMI', N'HYUNDAI', N'HDMU'),
(N'HDMU', N'HYUNDAI', N'HDMU'),
(N'HDSU', N'Kuehne & Nagel', N'KHNN'),
(N'HJCU', N'Hanjin Shipping', N'HJSC'),
(N'HJMU', N'GESeaCo', N'GESU'),
(N'HJSU', N'Hanjin Shipping', N'HJSC'),
(N'HLBU', N'HAPAG LLOYD', N'HPGC'),
(N'HLCU', N'HAPAG (HL)', N'HPGC'),
(N'HLRU', N'HAPAG (HL)', N'HPGC'),
(N'HLXU', N'HAPAG (HL)', N'HPGC'),
(N'HMCU', N'EVERGREEN', N'EGLV'),
(N'HMKU', N'W.E.C. Lines', N'WECU'),
(N'HMMU', N'HYUNDAI', N'HDMU'),
(N'HMRU', N'HYUNDAI', N'HDMU'),
(N'HMSU', N'Tarros', N'GETU'),
(N'HNKU', N'Textainer', N'TEXU'),
(N'HNPU', N'GESeaCo', N'GESU'),
(N'HNSU', N'Triton Container', N'YOIU'),
(N'HRZU', N'Matson', N'MATS'),
(N'HSTU', N'MACS', N'ELOU'),
(N'IAAU', N'Interasia Lines', N'IAAU'),
(N'ICSU', N'TAL International', N'TRLU'),
(N'IEAU', N'Cronos', N'LPIU'),
(N'IKKU', N'GESeaCo', N'GESU'),
(N'IKSU', N'TAL International', N'TRLU'),
(N'IMTU', N'ITALIA MARITTIMA', N'ITMA'),
(N'INBU', N'SeaCastle Inc', N'INBU'),
(N'INKU', N'SeaCastle Inc', N'INBU'),
(N'INNU', N'SeaCastle Inc', N'INBU'),
(N'INTU', N'SeaCastle Inc', N'INBU'),
(N'IOLU', N'Textainer', N'TEXU'),
(N'IPIU', N'IRISL', N'IRSU'),
(N'IPXU', N'SeaCastle Inc', N'INBU'),
(N'IRNU', N'SeaCastle Inc', N'INBU'),
(N'IRSO', N'IRISL', N'IRSU'),
(N'IRSU', N'IRISL', N'IRSU'),
(N'ITAU', N'HAPAG (HL)', N'HPGC'),
(N'ITLU', N'GESeaCo', N'GESU'),
(N'IVLU', N'HAPAG (HL)', N'HPGC'),
(N'JSSU', N'CNCo', N'CHVW'),
(N'JTMU', N'Florens', N'FBIU'),
(N'JXJU', N'ld Star Line', N'GSLU'),
(N'JXLU', N'ZIM', N'ZIMU'),
(N'KHJU', N'Hamburg Sud', N'SUDU'),
(N'KHLU', N'Hamburg Sud', N'SUDU'),
(N'KKFU', N'K-LINE', N'KKLU'),
(N'KKLU', N'K-LINE', N'KKLU'),
(N'KKTU', N'K-LINE', N'KKLU'),
(N'KLFU', N'K-LINE', N'KKLU'),
(N'KLTU', N'K-LINE', N'KKLU'),
(N'KMBU', N'Kambara Kisen', N'KMBU'),
(N'KMSU', N'YANG MING (YML)', N'YMLU'),
(N'KMTU', N'KMTC Line', N'KMTU'),
(N'KNLU', N'MAERSK', N'MAEU'),
(N'KOTO', N'DHL', N'DHLC'),
(N'KPPU', N'K-LINE', N'KKLU'),
(N'KWCU', N'Textainer', N'TEXU'),
(N'KXTU', N'K-LINE', N'KKLU'),
(N'LBIU', N'Libra', N'CLIB'),
(N'LCRU', N'CARU', N'WEDU'),
(N'LGEU', N'CARU', N'WEDU'),
(N'LLTU', N'Textainer', N'TEXU'),
(N'LLZU', N'Linea Messina', N'LMCU'),
(N'LMCU', N'Linea Messina', N'LMCU'),
(N'LNXU', N'CSAV NORASIA', N'NSLU'),
(N'LOTU', N'MAERSK', N'MAEU'),
(N'LPIU', N'Cronos', N'LPIU'),
(N'LTIU', N'ITALIA MARITTIMA', N'ITMA'),
(N'LYCU', N'DHL', N'DHLC'),
(N'LYKU', N'HAPAG (HL)', N'HPGC'),
(N'LYTU', N'HAPAG (HL)', N'HPGC'),
(N'MAEU', N'MAERSK', N'MAEU'),
(N'MAGU', N'Textainer', N'TEXU'),
(N'MALU', N'MAERSK', N'MAEU'),
(N'MANU', N'CARU', N'WEDU'),
(N'MARU', N'CARU', N'WEDU'),
(N'MATS', N'Matson', N'MATS'),
(N'MATU', N'Matson', N'MATS'),
(N'MAXU', N'Textainer', N'TEXU'),
(N'MBHU', N'Florens', N'FBIU'),
(N'MBIU', N'Bridgehead', N'BHCU'),
(N'MCAU', N'MAERSK', N'MAEU'),
(N'MCGU', N'MOL', N'MOLU'),
(N'MCHU', N'MAERSK', N'MAEU'),
(N'MCIU', N'MAERSK', N'MAEU'),
(N'MCRU', N'MAERSK', N'MAEU'),
(N'MCTU', N'MELL', N'MEL'),
(N'MEAU', N'MAERSK', N'MAEU'),
(N'MEDU', N'MSC', N'MSCU'),
(N'MERU', N'MELL', N'MEL'),
(N'MEXU', N'MELL', N'MEL'),
(N'MFRU', N'Marfret', N'MFUS'),
(N'MFTU', N'Marfret', N'MFUS'),
(N'MGBU', N'MAERSK', N'MAEU'),
(N'MGLU', N'Textainer', N'TEXU'),
(N'MGNU', N'SeaCastle Inc', N'INBU'),
(N'MHHU', N'MAERSK', N'MAEU'),
(N'MIEU', N'MAERSK', N'MAEU'),
(N'MLCU', N'Matson', N'MATS'),
(N'MLHU', N'Matson', N'MATS'),
(N'MMAU', N'MAERSK', N'MAEU'),
(N'MMCU', N'CMA CGM', N'CMDU'),
(N'MNBU', N'MAERSK', N'MAEU'),
(N'MOAU', N'MOL', N'MOLU'),
(N'MOCU', N'MACS', N'ELOU'),
(N'MOEU', N'MOL', N'MOLU'),
(N'MOFU', N'MOL', N'MOLU'),
(N'MOGC', N'MOL', N'MOLU'),
(N'MOGU', N'MOL', N'MOLU'),
(N'MOLU', N'MOL', N'MOLU'),
(N'MOMU', N'HAPAG LLOYD', N'HPGC'),
(N'MORU', N'MOL', N'MOLU'),
(N'MOSU', N'MOL', N'MOLU'),
(N'MOTU', N'MOL', N'MOLU'),
(N'MPCU', N'Samudera', N'SIKU'),
(N'MPWU', N'MAERSK', N'MAEU'),
(N'MRKU', N'MAERSK', N'MAEU'),
(N'MRLU', N'MAERSK', N'MAEU'),
(N'MRSU', N'MAERSK', N'MAEU'),
(N'MRTU', N'Meratus Line', N'MRTU'),
(N'MSAU', N'MAERSK', N'MAEU'),
(N'MSCU', N'MSC', N'MSCU'),
(N'MSDU', N'MSC', N'MSCU'),
(N'MSFU', N'MAERSK', N'MAEU'),
(N'MSKU', N'MAERSK', N'MAEU'),
(N'MSMU', N'MSC', N'MSCU'),
(N'MSNU', N'MSC', N'MSCU'),
(N'MSPU', N'MSC', N'MSCU'),
(N'MSTU', N'MSC', N'MSCU'),
(N'MSVU', N'MAERSK', N'MAEU'),
(N'MSWU', N'MAERSK', N'MAEU'),
(N'MSYU', N'MSC', N'MSCU'),
(N'MSZU', N'MSC', N'MSCU'),
(N'MTRU', N'TAL International', N'TRLU'),
(N'MTSU', N'SeaCastle Inc', N'INBU'),
(N'MTYU', N'SeaCastle Inc', N'INBU'),
(N'MVIU', N'MAERSK', N'MAEU'),
(N'MWCU', N'MAERSK', N'MAEU'),
(N'MWMU', N'MAERSK', N'MAEU'),
(N'MWSU', N'MAERSK', N'MAEU'),
(N'NDLU', N'MAERSK', N'MAEU'),
(N'NDSU', N'NileDutch', N'NIDU'),
(N'NENU', N'GRIEG STAR SHIPPING', N'GSSW'),
(N'NEPU', N'APL', N'APLU'),
(N'NEVU', N'CAI', N'CAXU'),
(N'NFRU', N'GRIEG STAR SHIPPING', N'GSSW'),
(N'NFWU', N'GRIEG STAR SHIPPING', N'GSSW'),
(N'NGNU', N'NYK Line', N'NYKS'),
(N'NIDU', N'NileDutch', N'NIDU'),
(N'NIRU', N'Nirint Shipping', N'NIRU'),
(N'NOLU', N'APL', N'APLU'),
(N'NOSU', N'APL', N'APLU'),
(N'NPFU', N'GRIEG STAR SHIPPING', N'GSSW'),
(N'NPJU', N'GRIEG STAR SHIPPING', N'GSSW'),
(N'NPRU', N'Sea Star Line', N'SSLH'),
(N'NPWU', N'GRIEG STAR SHIPPING', N'GSSW'),
(N'NSAU', N'NSCSA', N'NSAU'),
(N'NSAX', N'NSCSA', N'NSAU'),
(N'NSFU', N'Namsung', N'NSRU'),
(N'NSJU', N'Namsung', N'NSRU'),
(N'NSLU', N'CSAV NORASIA', N'NSLU'),
(N'NSOU', N'Namsung', N'NSRU'),
(N'NSRU', N'Namsung', N'NSRU'),
(N'NSSU', N'Namsung', N'NSRU'),
(N'NUIU', N'Triton Container', N'YOIU'),
(N'NUSU', N'APL', N'APLU'),
(N'NYKU', N'NYK Line', N'NYKS'),
(N'NYNU', N'NYK Line', N'NYKS'),
(N'NZCU', N'MAERSK', N'MAEU'),
(N'NZSU', N'MAERSK', N'MAEU'),
(N'OCLU', N'MAERSK', N'MAEU'),
(N'OCPU', N'MAERSK', N'MAEU'),
(N'OCTU', N'Samskip', N'SKII'),
(N'OFFU', N'CARU', N'WEDU'),
(N'ONEU', N'MOL', N'MOLU'),
(N'OOCL', N'OOCL', N'OOCO'),
(N'OOCU', N'OOCL', N'OOCO'),
(N'OOLU', N'OOCL', N'OOCO'),
(N'OPDU', N'CMA CGM', N'CMDU'),
(N'OTAU', N'CMA CGM', N'CMDU'),
(N'OTEU', N'CAI', N'CAXU'),
(N'OTPU', N'SeaCastle Inc', N'INBU'),
(N'OWNU', N'Tarros', N'GETU'),
(N'PALU', N'Pan Asia Line', N'PALU'),
(N'PANU', N'STX Pan Ocean', N'POBU'),
(N'PAXU', N'STX Pan Ocean', N'POBU'),
(N'PCIU', N'PIL', N'PCIU'),
(N'PCLU', N'PanCon', N'PCLU'),
(N'PCRU', N'HAPAG (HL)', N'HPGC'),
(N'PCSU', N'Dong Young Shipping', N'PCSU'),
(N'PDLU', N'Pacific Direct Line', N'PDLU'),
(N'PGHU', N'Pasha Hawaii', N'PSHI'),
(N'PGXU', N'Florens', N'FBIU'),
(N'PHLU', N'CN', N'TTWZ'),
(N'PILU', N'PIL', N'PCIU'),
(N'PLVU', N'HAPAG (HL)', N'HPGC'),
(N'PMLU', N'Perma Shipping Line', N'PMLU'),
(N'POBU', N'STX Pan Ocean', N'POBU'),
(N'POCU', N'MAERSK', N'MAEU'),
(N'POLU', N'STX Pan Ocean', N'POBU'),
(N'PONU', N'MAERSK', N'MAEU'),
(N'PRSU', N'Textainer', N'TEXU'),
(N'PSBU', N'HAPAG (HL)', N'HPGC'),
(N'PSCU', N'CARU', N'WEDU'),
(N'PXCU', N'K-LINE', N'KKLU'),
(N'QIBU', N'HAPAG LLOYD', N'HPGC'),
(N'QNNU', N'HAPAG LLOYD', N'HPGC'),
(N'RALU', N'Royal Arctic', N'RALU'),
(N'REGU', N'RCL', N'REGU'),
(N'RLWU', N'CARU', N'WEDU'),
(N'RMLU', N'Hamburg Sud', N'SUDU'),
(N'RRIU', N'Triton Container', N'YOIU'),
(N'RSLU', N'Matson', N'MATS'),
(N'RTHU', N'CARU', N'WEDU'),
(N'RZDU', N'TransContainer', N'TUSA'),
(N'SAFM', N'Safmarine', N'SAFM'),
(N'SANU', N'Samskip', N'SKII'),
(N'SBAU', N'IRISL', N'IRSU'),
(N'SBGU', N'Sea Star Line', N'SSLH'),
(N'SBOU', N'GESeaCo', N'GESU'),
(N'SCEU', N'GESeaCo', N'GESU'),
(N'SCMU', N'Safmarine', N'SAFM'),
(N'SCPU', N'GESeaCo', N'GESU'),
(N'SCSU', N'CARU', N'WEDU'),
(N'SCXU', N'GESeaCo', N'GESU'),
(N'SCZU', N'GESeaCo', N'GESU'),
(N'SDDU', N'SeaCastle Inc', N'INBU'),
(N'SEAU', N'MAERSK', N'MAEU'),
(N'SEDU', N'DB Schenker', N'SHKK'),
(N'SEFU', N'Crowley', N'CMCU'),
(N'SEGU', N'GESeaCo', N'GESU'),
(N'SEKU', N'GESeaCo', N'GESU'),
(N'SELU', N'GESeaCo', N'GESU'),
(N'SEMU', N'GESeaCo', N'GESU'),
(N'SENU', N'Hanjin Shipping', N'HJSC'),
(N'SIIU', N'SCI', N'SCIU'),
(N'SIKU', N'Samudera', N'SIKU'),
(N'SITU', N'SITC', N'SITU'),
(N'SITX', N'SITC', N'SITU'),
(N'SIUU', N'HAPAG (HL)', N'HPGC'),
(N'SJKU', N'SCLPL', N'SJKU'),
(N'SJXU', N'STX Pan Ocean', N'POBU'),
(N'SKHU', N'Sinokor', N'SKLU'),
(N'SKIU', N'Blue Sky', N'BSIU'),
(N'SKLU', N'Sinokor', N'SKLU'),
(N'SKNU', N'Kuehne & Nagel', N'KHNN'),
(N'SKRU', N'Sinokor', N'SKLU'),
(N'SKSU', N'Sinokor', N'SKLU'),
(N'SKYU', N'CAI', N'CAXU'),
(N'SLMU', N'LD', N'GLDU'),
(N'SLSU', N'CN', N'TTWZ'),
(N'SMLU', N'Seaboard Marine', N'SMLU'),
(N'SPKU', N'CN', N'TTWZ'),
(N'SPLU', N'GESeaCo', N'GESU'),
(N'SPNU', N'SPIL', N'SPNU'),
(N'STJU', N'DB Schenker', N'SHKK'),
(N'STMU', N'CMA CGM', N'CMDU'),
(N'STRU', N'Sea Star Line', N'SSLH'),
(N'STXU', N'STX Pan Ocean', N'POBU'),
(N'SUDU', N'Hamburg Sud', N'SUDU'),
(N'SVDU', N'Samskip', N'SKII'),
(N'SWLU', N'Samskip', N'SKII'),
(N'SZLU', N'SeaCastle Inc', N'INBU'),
(N'TAKU', N'Tanto', N'TAKU'),
(N'TARU', N'Tarros', N'GETU'),
(N'TCKU', N'Triton Container', N'YOIU'),
(N'TCLU', N'TAL International', N'TRLU'),
(N'TCNU', N'Triton Container', N'YOIU'),
(N'TCVU', N'Florens', N'FBIU'),
(N'TDRU', N'TAL International', N'TRLU'),
(N'TDTU', N'TAL International', N'TRLU'),
(N'TEHU', N'TAL International', N'TRLU'),
(N'TEMU', N'Textainer', N'TEXU'),
(N'TENU', N'Textainer', N'TEXU'),
(N'TEXU', N'Textainer', N'TEXU'),
(N'TFHU', N'DHL', N'DHLC'),
(N'TGBU', N'Textainer', N'TEXU'),
(N'TGHI', N'Textainer', N'TEXU'),
(N'TGHU', N'Textainer', N'TEXU'),
(N'TGHY', N'Textainer', N'TEXU'),
(N'TIIU', N'Triton Container', N'YOIU'),
(N'TINB', N'GESeaCo', N'GESU'),
(N'TINT', N'GESeaCo', N'GESU'),
(N'TKRU', N'TransContainer', N'TUSA'),
(N'TLEU', N'HAPAG (HL)', N'HPGC'),
(N'TLLU', N'TAL International', N'TRLU'),
(N'TLXU', N'Trans Asia', N'TLXU'),
(N'TMCU', N'Transmar', N'TRMU'),
(N'TMMU', N'HAPAG (HL)', N'HPGC'),
(N'TNDU', N'T.S. Lines', N'TSQD'),
(N'TOLU', N'TAL International', N'TRLU'),
(N'TORU', N'MAERSK', N'MAEU'),
(N'TPCU', N'Wan Hai Lines', N'WHSU'),
(N'TPHU', N'TAL International', N'TRLU'),
(N'TPXU', N'TAL International', N'TRLU'),
(N'TRBU', N'Trailer Bridge', N'TRLD'),
(N'TRDU', N'TAL International', N'TRLU'),
(N'TRHU', N'Triton Container', N'YOIU'),
(N'TRIU', N'Triton Container', N'YOIU'),
(N'TRKU', N'Turkon', N'TUKN'),
(N'TRLP', N'TAL International', N'TRLU'),
(N'TRLU', N'TAL International', N'TRLU'),
(N'TRTU', N'CARU', N'WEDU'),
(N'TRVU', N'Triton Container', N'YOIU'),
(N'TSLU', N'T.S. Lines', N'TSQD'),
(N'TSTU', N'T.S. Lines', N'TSQD'),
(N'TTNU', N'Triton Container', N'YOIU'),
(N'TURK', N'Turkon', N'TUKN'),
(N'TWSU', N'Florens', N'FBIU'),
(N'TXGU', N'Textainer', N'TEXU'),
(N'TXSU', N'GESeaCo', N'GESU'),
(N'UACU', N'HAPAG LLOYD', N'HPGC'),
(N'UAEU', N'HAPAG LLOYD', N'HPGC'),
(N'UASU', N'HAPAG LLOYD', N'HPGC'),
(N'UESU', N'UES', N'UETU'),
(N'UETU', N'UES', N'UETU'),
(N'UFCU', N'GESeaCo', N'GESU'),
(N'UGMU', N'EVERGREEN', N'EGLV'),
(N'USCU', N'HAPAG (HL)', N'HPGC'),
(N'UTCU', N'CMA CGM', N'CMDU'),
(N'UXXU', N'UES', N'UETU'),
(N'VDMU', N'Samskip', N'SKII'),
(N'VECU', N'CARU', N'WEDU'),
(N'WBPU', N'SeaCastle Inc', N'INBU'),
(N'WCIU', N'Textainer', N'TEXU'),
(N'WCXU', N'W.E.C. Lines', N'WECU'),
(N'WECU', N'W.E.C. Lines', N'WECU'),
(N'WEDU', N'CARU', N'WEDU'),
(N'WFHU', N'Waterfront Container', N'WFHU'),
(N'WHLU', N'Wan Hai Lines', N'WHSU'),
(N'WHSU', N'Wan Hai Lines', N'WHSU'),
(N'WIKU', N'Textainer', N'TEXU'),
(N'WSCU', N'CARU', N'WEDU'),
(N'WTLU', N'White Line', N'WTLU'),
(N'XBIU', N'IRISL', N'IRSU'),
(N'XCLU', N'Textainer', N'TEXU'),
(N'XINU', N'Textainer', N'TEXU'),
(N'XTRU', N'GESeaCo', N'GESU'),
(N'YMLU', N'YANG MING (YML)', N'YMLU'),
(N'YMMU', N'YANG MING (YML)', N'YMLU'),
(N'YOIU', N'Triton Container', N'YOIU'),
(N'ZBXU', N'ZIM', N'ZIMU'),
(N'ZCLU', N'ZIM', N'ZIMU'),
(N'ZCSU', N'ZIM', N'ZIMU'),
(N'ZIMU', N'ZIM', N'ZIMU'),
(N'ZMOU', N'ZIM', N'ZIMU'),
(N'ZWFU', N'ZIM', N'ZIMU')