
CREATE TABLE [dbo].[ASNETAUpdate](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AsnNo] [varchar](25) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[InitialEta] [datetime] NULL,
	[UpdatedEta] [datetime] NOT NULL,
 CONSTRAINT [PK_ASNETAUpdate] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO