ALTER TABLE dbi.iLogIntegrationBox
    ADD
        ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
            CONSTRAINT DF_iLogIntegrationBox_ValidFrom DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
            CONSTRAINT DF_iLogIntegrationBox_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    PERIOD FOR SYSTEM_TIME(ValidFrom, ValidTo);
GO

ALTER TABLE dbi.iLogIntegrationBox
    SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbi.iLogIntegrationBoxHistory));
GO