BEGIN
	CREATE TABLE ASNShippingInfoTSC(
		ASNNo VARCHAR(25) NOT NULL,
		ETAToHub DATETIME NULL,
		CONSTRAINT PK_ASNShippingInfoTSC_ASNNo PRIMARY KEY(ASNNo),
		UpdatedDate DATETIME NOT NULL CONSTRAINT DF_ASNShippingInfoTSC_UpdatedDate DEFAULT GETDATE(),
		CreatedDate DATETIME NOT NULL CONSTRAINT DF_ASNShippingInfoTSC_CreatedDate DEFAULT GETDATE(),
	);
END