BEGIN 
	CREATE TABLE TT_ELLISPalletType (
		Id INT IDENTITY(1,1) PRIMARY KEY,
		Name VARCHAR(255) NOT NULL
	);

	ALTER TABLE TT_PartMaster
	ADD ELLISPalletTypeId INT NOT NULL
	CONSTRAINT DF_TT_PartMaster_ELLISPalletTypeId DEFAULT(0)
	
	SET IDENTITY_INSERT TT_ELLISPalletType ON;
	INSERT INTO TT_ELLISPalletType(Id, Name) VALUES
		(0, 'BLK-01');
	SET IDENTITY_INSERT TT_ELLISPalletType OFF;

	ALTER TABLE TT_PartMaster
	ADD CONSTRAINT FK_TT_PartMaster_ELLISPalletTypeId FOREIGN KEY(ELLISPalletTypeId) REFERENCES TT_ELLISPalletType(Id)
END
