# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  - master
  
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: dotnet publish
  inputs:
    workingDirectory: ./src/Presentation
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: False
- task: DotNetCoreCLI@2
  displayName: run tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: PublishPipelineArtifact@1
  displayName: publish arifacts - application
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'tt-api'
- task: PublishPipelineArtifact@1
  displayName: publish arifacts - config
  inputs:
    targetPath: ./config
    artifactName: 'config'